### ISSUE TITLE
Tela de anotações não suporta quebras de linha

### ISSUE THREAD

**Issue by girol** [df-ffclrp/SisDF#1]
- Modificar a tela de anotações do chamado, no painel de atendimento do técnico quebras de linha
- Modificar campo de descrição do chamado para suportar quebras de linha

**Comment by jppcel** [comment]
@girol No caso o banco de dados do sistema é o MySQL/MariaDB né?

**Comment by girol** [comment]
@jppcel, sim :)

**Comment by jppcel** [comment]
Não seria melhor que o campo de descrição fosse text ao invés de varchar(500)[Como isso aconteceu?]?

**Comment by jppcel** [comment]
https://github.com/df-ffclrp/SisDF/blob/master/SQL/sisdf_create.sql#L147

**Comment by girol** [comment]
G_G Cara, com certeza. Eu modelei pelo MySQL Workbench, devo ter cometido um erro na hora de criar o campo. Essa tabela eu recriei algumas vezes. Valeu pelo aviso :D
