### ISSUE TITLE
Relator não pode adicionar andamento do chamado.

### ISSUE THREAD

**Issue by masakik** [df-ffclrp/SisDF#14]
Não seria o caso do relator (pessoa que abriu o chamado) poder acrescentar informação no andamento?

**Comment by girol** [comment]
Isso é algo a se discutir. A ideia concebida seria apenas pro técnico adicionar as tarefas. Mas é facilmente implementável.

**Comment by masakik** [comment]
Imaginei uma situação onde o técnico faz um atendimento mas falta alguma peça. O técnico relata isso e fica no aguardo da chegada da peça. Quando chegar o relator acrescenta essa informação para dar continuidade ao atendimento.

**Comment by girol** [comment]
Mas isso quem acaba adicionando é o próprio técnico. Um caso real aqui:

Pifou um HD de um servidor. Testei e vi que era o HD mesmo. Coloquei o chamado "em espera" e adicionei a falta da peça. Normalmente o relator, pelo menos aqui na minha unidade, raramente comunica modificações no andamento do chamado. De qualquer forma é algo bem simples de implementar na base de código atual.

**Comment by masakik** [comment]
Entendido. Se esse é o modo normal de operação tranquilo.
