### ISSUE TITLE
Limitar campo "Resumo" do formulário de abertura de chamados

### ISSUE THREAD

**Issue by girol** [df-ffclrp/SisDF#4]
O formulário está deixando cadastrar mais caracteres que o permitido no banco.

**Comment by jppcel** [comment]
Olá,
Enviei uma solução pelo pull request #6.
Implementei a limitação via HTML, pois via PHP poderia dar algum problema caso o último caractere seja um caractere especial.

**Comment by girol** [comment]
Olá! @jppcel primeiramente, muito obrigado por sua contribuição.

Logo faço o merge!

[]s!

**Comment by girol** [comment]
Ah, outra coisa: era pra limitar no HTML mesmo, acho que já é suficiente :)
